# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ainstein_radar_msgs/RadarTrackedObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ainstein_radar_msgs.msg
import geometry_msgs.msg

class RadarTrackedObject(genpy.Message):
  _md5sum = "2a71462f8c844a31b18d0564b8ff5905"
  _type = "ainstein_radar_msgs/RadarTrackedObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This message describes a tracked object from a RADAR sensor.

uint16 id                    # Unique object identifier

geometry_msgs/Pose pose      # Cartesian position and orientation
geometry_msgs/Twist velocity # Cartesian linear and angular velocity (twist)

BoundingBox box              # Bounding box of associated raw detections
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: ainstein_radar_msgs/BoundingBox
# BoundingBox represents a oriented bounding box.
geometry_msgs/Pose pose
geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)
# You can use this field to hold value such as likelihood
float32 value
uint32 label"""
  __slots__ = ['id','pose','velocity','box']
  _slot_types = ['uint16','geometry_msgs/Pose','geometry_msgs/Twist','ainstein_radar_msgs/BoundingBox']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,pose,velocity,box

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarTrackedObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.box is None:
        self.box = ainstein_radar_msgs.msg.BoundingBox()
    else:
      self.id = 0
      self.pose = geometry_msgs.msg.Pose()
      self.velocity = geometry_msgs.msg.Twist()
      self.box = ainstein_radar_msgs.msg.BoundingBox()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_H23dfI().pack(_x.id, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.dimensions.x, _x.box.dimensions.y, _x.box.dimensions.z, _x.box.value, _x.box.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.box is None:
        self.box = ainstein_radar_msgs.msg.BoundingBox()
      end = 0
      _x = self
      start = end
      end += 194
      (_x.id, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.dimensions.x, _x.box.dimensions.y, _x.box.dimensions.z, _x.box.value, _x.box.label,) = _get_struct_H23dfI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_H23dfI().pack(_x.id, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.dimensions.x, _x.box.dimensions.y, _x.box.dimensions.z, _x.box.value, _x.box.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.box is None:
        self.box = ainstein_radar_msgs.msg.BoundingBox()
      end = 0
      _x = self
      start = end
      end += 194
      (_x.id, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.dimensions.x, _x.box.dimensions.y, _x.box.dimensions.z, _x.box.value, _x.box.label,) = _get_struct_H23dfI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H23dfI = None
def _get_struct_H23dfI():
    global _struct_H23dfI
    if _struct_H23dfI is None:
        _struct_H23dfI = struct.Struct("<H23dfI")
    return _struct_H23dfI
