# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ainstein_radar_msgs/RadarTrackedObjectStamped.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ainstein_radar_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class RadarTrackedObjectStamped(genpy.Message):
  _md5sum = "f602f4531922144f087b6812eed02f3e"
  _type = "ainstein_radar_msgs/RadarTrackedObjectStamped"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# This message describes a tracked object with a timestamp.

std_msgs/Header header

RadarTrackedObject object

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ainstein_radar_msgs/RadarTrackedObject
# This message describes a tracked object from a RADAR sensor.

uint16 id                    # Unique object identifier

geometry_msgs/Pose pose      # Cartesian position and orientation
geometry_msgs/Twist velocity # Cartesian linear and angular velocity (twist)

BoundingBox box              # Bounding box of associated raw detections
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: ainstein_radar_msgs/BoundingBox
# BoundingBox represents a oriented bounding box.
geometry_msgs/Pose pose
geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)
# You can use this field to hold value such as likelihood
float32 value
uint32 label"""
  __slots__ = ['header','object']
  _slot_types = ['std_msgs/Header','ainstein_radar_msgs/RadarTrackedObject']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,object

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarTrackedObjectStamped, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = ainstein_radar_msgs.msg.RadarTrackedObject()
    else:
      self.header = std_msgs.msg.Header()
      self.object = ainstein_radar_msgs.msg.RadarTrackedObject()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_H23dfI().pack(_x.object.id, _x.object.pose.position.x, _x.object.pose.position.y, _x.object.pose.position.z, _x.object.pose.orientation.x, _x.object.pose.orientation.y, _x.object.pose.orientation.z, _x.object.pose.orientation.w, _x.object.velocity.linear.x, _x.object.velocity.linear.y, _x.object.velocity.linear.z, _x.object.velocity.angular.x, _x.object.velocity.angular.y, _x.object.velocity.angular.z, _x.object.box.pose.position.x, _x.object.box.pose.position.y, _x.object.box.pose.position.z, _x.object.box.pose.orientation.x, _x.object.box.pose.orientation.y, _x.object.box.pose.orientation.z, _x.object.box.pose.orientation.w, _x.object.box.dimensions.x, _x.object.box.dimensions.y, _x.object.box.dimensions.z, _x.object.box.value, _x.object.box.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = ainstein_radar_msgs.msg.RadarTrackedObject()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 194
      (_x.object.id, _x.object.pose.position.x, _x.object.pose.position.y, _x.object.pose.position.z, _x.object.pose.orientation.x, _x.object.pose.orientation.y, _x.object.pose.orientation.z, _x.object.pose.orientation.w, _x.object.velocity.linear.x, _x.object.velocity.linear.y, _x.object.velocity.linear.z, _x.object.velocity.angular.x, _x.object.velocity.angular.y, _x.object.velocity.angular.z, _x.object.box.pose.position.x, _x.object.box.pose.position.y, _x.object.box.pose.position.z, _x.object.box.pose.orientation.x, _x.object.box.pose.orientation.y, _x.object.box.pose.orientation.z, _x.object.box.pose.orientation.w, _x.object.box.dimensions.x, _x.object.box.dimensions.y, _x.object.box.dimensions.z, _x.object.box.value, _x.object.box.label,) = _get_struct_H23dfI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_H23dfI().pack(_x.object.id, _x.object.pose.position.x, _x.object.pose.position.y, _x.object.pose.position.z, _x.object.pose.orientation.x, _x.object.pose.orientation.y, _x.object.pose.orientation.z, _x.object.pose.orientation.w, _x.object.velocity.linear.x, _x.object.velocity.linear.y, _x.object.velocity.linear.z, _x.object.velocity.angular.x, _x.object.velocity.angular.y, _x.object.velocity.angular.z, _x.object.box.pose.position.x, _x.object.box.pose.position.y, _x.object.box.pose.position.z, _x.object.box.pose.orientation.x, _x.object.box.pose.orientation.y, _x.object.box.pose.orientation.z, _x.object.box.pose.orientation.w, _x.object.box.dimensions.x, _x.object.box.dimensions.y, _x.object.box.dimensions.z, _x.object.box.value, _x.object.box.label))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = ainstein_radar_msgs.msg.RadarTrackedObject()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 194
      (_x.object.id, _x.object.pose.position.x, _x.object.pose.position.y, _x.object.pose.position.z, _x.object.pose.orientation.x, _x.object.pose.orientation.y, _x.object.pose.orientation.z, _x.object.pose.orientation.w, _x.object.velocity.linear.x, _x.object.velocity.linear.y, _x.object.velocity.linear.z, _x.object.velocity.angular.x, _x.object.velocity.angular.y, _x.object.velocity.angular.z, _x.object.box.pose.position.x, _x.object.box.pose.position.y, _x.object.box.pose.position.z, _x.object.box.pose.orientation.x, _x.object.box.pose.orientation.y, _x.object.box.pose.orientation.z, _x.object.box.pose.orientation.w, _x.object.box.dimensions.x, _x.object.box.dimensions.y, _x.object.box.dimensions.z, _x.object.box.value, _x.object.box.label,) = _get_struct_H23dfI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_H23dfI = None
def _get_struct_H23dfI():
    global _struct_H23dfI
    if _struct_H23dfI is None:
        _struct_H23dfI = struct.Struct("<H23dfI")
    return _struct_H23dfI
