# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ainstein_radar_drivers/O79TrackingParams.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class O79TrackingParams(genpy.Message):
  _md5sum = "8794997c1f9ccf549a183253ff0fcb2e"
  _type = "ainstein_radar_drivers/O79TrackingParams"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This message describes the O-79 imaging radar tracking filter parameters.

float32 update_rate
float32 min_time
float32 timeout
float32 confidence_level
float32 proc_noise_speed
float32 proc_noise_azim
float32 proc_noise_elev
float32 min_range
float32 max_range
float32 proc_noise_vel_x
float32 proc_noise_vel_y
float32 proc_noise_vel_z
float32 meas_noise_speed
float32 meas_noise_pos
int8 filter_type"""
  __slots__ = ['update_rate','min_time','timeout','confidence_level','proc_noise_speed','proc_noise_azim','proc_noise_elev','min_range','max_range','proc_noise_vel_x','proc_noise_vel_y','proc_noise_vel_z','meas_noise_speed','meas_noise_pos','filter_type']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       update_rate,min_time,timeout,confidence_level,proc_noise_speed,proc_noise_azim,proc_noise_elev,min_range,max_range,proc_noise_vel_x,proc_noise_vel_y,proc_noise_vel_z,meas_noise_speed,meas_noise_pos,filter_type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(O79TrackingParams, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.update_rate is None:
        self.update_rate = 0.
      if self.min_time is None:
        self.min_time = 0.
      if self.timeout is None:
        self.timeout = 0.
      if self.confidence_level is None:
        self.confidence_level = 0.
      if self.proc_noise_speed is None:
        self.proc_noise_speed = 0.
      if self.proc_noise_azim is None:
        self.proc_noise_azim = 0.
      if self.proc_noise_elev is None:
        self.proc_noise_elev = 0.
      if self.min_range is None:
        self.min_range = 0.
      if self.max_range is None:
        self.max_range = 0.
      if self.proc_noise_vel_x is None:
        self.proc_noise_vel_x = 0.
      if self.proc_noise_vel_y is None:
        self.proc_noise_vel_y = 0.
      if self.proc_noise_vel_z is None:
        self.proc_noise_vel_z = 0.
      if self.meas_noise_speed is None:
        self.meas_noise_speed = 0.
      if self.meas_noise_pos is None:
        self.meas_noise_pos = 0.
      if self.filter_type is None:
        self.filter_type = 0
    else:
      self.update_rate = 0.
      self.min_time = 0.
      self.timeout = 0.
      self.confidence_level = 0.
      self.proc_noise_speed = 0.
      self.proc_noise_azim = 0.
      self.proc_noise_elev = 0.
      self.min_range = 0.
      self.max_range = 0.
      self.proc_noise_vel_x = 0.
      self.proc_noise_vel_y = 0.
      self.proc_noise_vel_z = 0.
      self.meas_noise_speed = 0.
      self.meas_noise_pos = 0.
      self.filter_type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_14fb().pack(_x.update_rate, _x.min_time, _x.timeout, _x.confidence_level, _x.proc_noise_speed, _x.proc_noise_azim, _x.proc_noise_elev, _x.min_range, _x.max_range, _x.proc_noise_vel_x, _x.proc_noise_vel_y, _x.proc_noise_vel_z, _x.meas_noise_speed, _x.meas_noise_pos, _x.filter_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 57
      (_x.update_rate, _x.min_time, _x.timeout, _x.confidence_level, _x.proc_noise_speed, _x.proc_noise_azim, _x.proc_noise_elev, _x.min_range, _x.max_range, _x.proc_noise_vel_x, _x.proc_noise_vel_y, _x.proc_noise_vel_z, _x.meas_noise_speed, _x.meas_noise_pos, _x.filter_type,) = _get_struct_14fb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_14fb().pack(_x.update_rate, _x.min_time, _x.timeout, _x.confidence_level, _x.proc_noise_speed, _x.proc_noise_azim, _x.proc_noise_elev, _x.min_range, _x.max_range, _x.proc_noise_vel_x, _x.proc_noise_vel_y, _x.proc_noise_vel_z, _x.meas_noise_speed, _x.meas_noise_pos, _x.filter_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 57
      (_x.update_rate, _x.min_time, _x.timeout, _x.confidence_level, _x.proc_noise_speed, _x.proc_noise_azim, _x.proc_noise_elev, _x.min_range, _x.max_range, _x.proc_noise_vel_x, _x.proc_noise_vel_y, _x.proc_noise_vel_z, _x.meas_noise_speed, _x.meas_noise_pos, _x.filter_type,) = _get_struct_14fb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14fb = None
def _get_struct_14fb():
    global _struct_14fb
    if _struct_14fb is None:
        _struct_14fb = struct.Struct("<14fb")
    return _struct_14fb
