# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ainstein_radar_drivers/WayvAirConfiguration.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WayvAirConfiguration(genpy.Message):
  _md5sum = "697324bcda4e9dd0d2b06e834f223a42"
  _type = "ainstein_radar_drivers/WayvAirConfiguration"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This message describes the Wayv Air radar configuration parameters.
string fw_ver           # Firmware Version
string sbl_ver          # Bootloader Version
uint16 id_485           # 485 ID / Radar Comm ID
uint32 baud_485         # Serial Baud Rate
string server_ip        # Server IP address for Station Mode
uint16 server_port      # Server Port for Station Mode
string wifi_name        # WAYV (AP) broadcast Wifi Name
string wifi_pwd         # WAYV (AP) Broadcast Wifi Password
string con_wifi_name    # Station Mode Wifi Name
string con_wifi_pwd     # Station Mode Wifi Password
string dev_id           # Device Serial ID
uint16 wifi_mode        # AP mode (0) or Station mode(1)
uint16 sys_mode         # WAYV Operating Mode - Normal(0) - TLV(2) - TLV_Wifi(4)
uint16 radio_switch     # Radio Inactive (0) - Radio Inactive (1)
uint16 radio_time       #
string[] radar_conf       # Radar Configuration String
uint16 radar_config_len # Number of Radar Config Entries"""
  __slots__ = ['fw_ver','sbl_ver','id_485','baud_485','server_ip','server_port','wifi_name','wifi_pwd','con_wifi_name','con_wifi_pwd','dev_id','wifi_mode','sys_mode','radio_switch','radio_time','radar_conf','radar_config_len']
  _slot_types = ['string','string','uint16','uint32','string','uint16','string','string','string','string','string','uint16','uint16','uint16','uint16','string[]','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fw_ver,sbl_ver,id_485,baud_485,server_ip,server_port,wifi_name,wifi_pwd,con_wifi_name,con_wifi_pwd,dev_id,wifi_mode,sys_mode,radio_switch,radio_time,radar_conf,radar_config_len

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WayvAirConfiguration, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.fw_ver is None:
        self.fw_ver = ''
      if self.sbl_ver is None:
        self.sbl_ver = ''
      if self.id_485 is None:
        self.id_485 = 0
      if self.baud_485 is None:
        self.baud_485 = 0
      if self.server_ip is None:
        self.server_ip = ''
      if self.server_port is None:
        self.server_port = 0
      if self.wifi_name is None:
        self.wifi_name = ''
      if self.wifi_pwd is None:
        self.wifi_pwd = ''
      if self.con_wifi_name is None:
        self.con_wifi_name = ''
      if self.con_wifi_pwd is None:
        self.con_wifi_pwd = ''
      if self.dev_id is None:
        self.dev_id = ''
      if self.wifi_mode is None:
        self.wifi_mode = 0
      if self.sys_mode is None:
        self.sys_mode = 0
      if self.radio_switch is None:
        self.radio_switch = 0
      if self.radio_time is None:
        self.radio_time = 0
      if self.radar_conf is None:
        self.radar_conf = []
      if self.radar_config_len is None:
        self.radar_config_len = 0
    else:
      self.fw_ver = ''
      self.sbl_ver = ''
      self.id_485 = 0
      self.baud_485 = 0
      self.server_ip = ''
      self.server_port = 0
      self.wifi_name = ''
      self.wifi_pwd = ''
      self.con_wifi_name = ''
      self.con_wifi_pwd = ''
      self.dev_id = ''
      self.wifi_mode = 0
      self.sys_mode = 0
      self.radio_switch = 0
      self.radio_time = 0
      self.radar_conf = []
      self.radar_config_len = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.fw_ver
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.sbl_ver
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_HI().pack(_x.id_485, _x.baud_485))
      _x = self.server_ip
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.server_port
      buff.write(_get_struct_H().pack(_x))
      _x = self.wifi_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.wifi_pwd
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.con_wifi_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.con_wifi_pwd
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.dev_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4H().pack(_x.wifi_mode, _x.sys_mode, _x.radio_switch, _x.radio_time))
      length = len(self.radar_conf)
      buff.write(_struct_I.pack(length))
      for val1 in self.radar_conf:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      _x = self.radar_config_len
      buff.write(_get_struct_H().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.fw_ver = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.fw_ver = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sbl_ver = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sbl_ver = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.id_485, _x.baud_485,) = _get_struct_HI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.server_ip = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.server_ip = str[start:end]
      start = end
      end += 2
      (self.server_port,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.wifi_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.wifi_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.wifi_pwd = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.wifi_pwd = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.con_wifi_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.con_wifi_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.con_wifi_pwd = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.con_wifi_pwd = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dev_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dev_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.wifi_mode, _x.sys_mode, _x.radio_switch, _x.radio_time,) = _get_struct_4H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.radar_conf = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.radar_conf.append(val1)
      start = end
      end += 2
      (self.radar_config_len,) = _get_struct_H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.fw_ver
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.sbl_ver
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_HI().pack(_x.id_485, _x.baud_485))
      _x = self.server_ip
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.server_port
      buff.write(_get_struct_H().pack(_x))
      _x = self.wifi_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.wifi_pwd
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.con_wifi_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.con_wifi_pwd
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.dev_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4H().pack(_x.wifi_mode, _x.sys_mode, _x.radio_switch, _x.radio_time))
      length = len(self.radar_conf)
      buff.write(_struct_I.pack(length))
      for val1 in self.radar_conf:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      _x = self.radar_config_len
      buff.write(_get_struct_H().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.fw_ver = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.fw_ver = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sbl_ver = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sbl_ver = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.id_485, _x.baud_485,) = _get_struct_HI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.server_ip = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.server_ip = str[start:end]
      start = end
      end += 2
      (self.server_port,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.wifi_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.wifi_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.wifi_pwd = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.wifi_pwd = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.con_wifi_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.con_wifi_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.con_wifi_pwd = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.con_wifi_pwd = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dev_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dev_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.wifi_mode, _x.sys_mode, _x.radio_switch, _x.radio_time,) = _get_struct_4H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.radar_conf = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.radar_conf.append(val1)
      start = end
      end += 2
      (self.radar_config_len,) = _get_struct_H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4H = None
def _get_struct_4H():
    global _struct_4H
    if _struct_4H is None:
        _struct_4H = struct.Struct("<4H")
    return _struct_4H
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
_struct_HI = None
def _get_struct_HI():
    global _struct_HI
    if _struct_HI is None:
        _struct_HI = struct.Struct("<HI")
    return _struct_HI
