// Generated by gencpp from file open3d_slam_msgs/SaveSubmaps.msg
// DO NOT EDIT!


#ifndef OPEN3D_SLAM_MSGS_MESSAGE_SAVESUBMAPS_H
#define OPEN3D_SLAM_MSGS_MESSAGE_SAVESUBMAPS_H

#include <ros/service_traits.h>


#include <open3d_slam_msgs/SaveSubmapsRequest.h>
#include <open3d_slam_msgs/SaveSubmapsResponse.h>


namespace open3d_slam_msgs
{

struct SaveSubmaps
{

typedef SaveSubmapsRequest Request;
typedef SaveSubmapsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveSubmaps
} // namespace open3d_slam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open3d_slam_msgs::SaveSubmaps > {
  static const char* value()
  {
    return "9e836a97d829a00e348178b9b373d448";
  }

  static const char* value(const ::open3d_slam_msgs::SaveSubmaps&) { return value(); }
};

template<>
struct DataType< ::open3d_slam_msgs::SaveSubmaps > {
  static const char* value()
  {
    return "open3d_slam_msgs/SaveSubmaps";
  }

  static const char* value(const ::open3d_slam_msgs::SaveSubmaps&) { return value(); }
};


// service_traits::MD5Sum< ::open3d_slam_msgs::SaveSubmapsRequest> should match
// service_traits::MD5Sum< ::open3d_slam_msgs::SaveSubmaps >
template<>
struct MD5Sum< ::open3d_slam_msgs::SaveSubmapsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open3d_slam_msgs::SaveSubmaps >::value();
  }
  static const char* value(const ::open3d_slam_msgs::SaveSubmapsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open3d_slam_msgs::SaveSubmapsRequest> should match
// service_traits::DataType< ::open3d_slam_msgs::SaveSubmaps >
template<>
struct DataType< ::open3d_slam_msgs::SaveSubmapsRequest>
{
  static const char* value()
  {
    return DataType< ::open3d_slam_msgs::SaveSubmaps >::value();
  }
  static const char* value(const ::open3d_slam_msgs::SaveSubmapsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open3d_slam_msgs::SaveSubmapsResponse> should match
// service_traits::MD5Sum< ::open3d_slam_msgs::SaveSubmaps >
template<>
struct MD5Sum< ::open3d_slam_msgs::SaveSubmapsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open3d_slam_msgs::SaveSubmaps >::value();
  }
  static const char* value(const ::open3d_slam_msgs::SaveSubmapsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open3d_slam_msgs::SaveSubmapsResponse> should match
// service_traits::DataType< ::open3d_slam_msgs::SaveSubmaps >
template<>
struct DataType< ::open3d_slam_msgs::SaveSubmapsResponse>
{
  static const char* value()
  {
    return DataType< ::open3d_slam_msgs::SaveSubmaps >::value();
  }
  static const char* value(const ::open3d_slam_msgs::SaveSubmapsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN3D_SLAM_MSGS_MESSAGE_SAVESUBMAPS_H
