// Generated by gencpp from file open3d_slam_msgs/SaveMapResponse.msg
// DO NOT EDIT!


#ifndef OPEN3D_SLAM_MSGS_MESSAGE_SAVEMAPRESPONSE_H
#define OPEN3D_SLAM_MSGS_MESSAGE_SAVEMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open3d_slam_msgs
{
template <class ContainerAllocator>
struct SaveMapResponse_
{
  typedef SaveMapResponse_<ContainerAllocator> Type;

  SaveMapResponse_()
    : statusMessage()  {
    }
  SaveMapResponse_(const ContainerAllocator& _alloc)
    : statusMessage(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _statusMessage_type;
  _statusMessage_type statusMessage;





  typedef boost::shared_ptr< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMapResponse_

typedef ::open3d_slam_msgs::SaveMapResponse_<std::allocator<void> > SaveMapResponse;

typedef boost::shared_ptr< ::open3d_slam_msgs::SaveMapResponse > SaveMapResponsePtr;
typedef boost::shared_ptr< ::open3d_slam_msgs::SaveMapResponse const> SaveMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator1> & lhs, const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.statusMessage == rhs.statusMessage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator1> & lhs, const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace open3d_slam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e836a97d829a00e348178b9b373d448";
  }

  static const char* value(const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e836a97d829a00eULL;
  static const uint64_t static_value2 = 0x348178b9b373d448ULL;
};

template<class ContainerAllocator>
struct DataType< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open3d_slam_msgs/SaveMapResponse";
  }

  static const char* value(const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string statusMessage\n"
;
  }

  static const char* value(const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.statusMessage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open3d_slam_msgs::SaveMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "statusMessage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.statusMessage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN3D_SLAM_MSGS_MESSAGE_SAVEMAPRESPONSE_H
