// Generated by gencpp from file ainstein_radar_msgs/BoundingBoxStamped.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_BOUNDINGBOXSTAMPED_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_BOUNDINGBOXSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ainstein_radar_msgs/BoundingBox.h>

namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct BoundingBoxStamped_
{
  typedef BoundingBoxStamped_<ContainerAllocator> Type;

  BoundingBoxStamped_()
    : header()
    , box()  {
    }
  BoundingBoxStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , box(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ainstein_radar_msgs::BoundingBox_<ContainerAllocator>  _box_type;
  _box_type box;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBoxStamped_

typedef ::ainstein_radar_msgs::BoundingBoxStamped_<std::allocator<void> > BoundingBoxStamped;

typedef boost::shared_ptr< ::ainstein_radar_msgs::BoundingBoxStamped > BoundingBoxStampedPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::BoundingBoxStamped const> BoundingBoxStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.box == rhs.box;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "259e334973915dc19ccfbff4a8ead75e";
  }

  static const char* value(const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x259e334973915dc1ULL;
  static const uint64_t static_value2 = 0x9ccfbff4a8ead75eULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/BoundingBoxStamped";
  }

  static const char* value(const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# BoundingBoxStamped is a stamped BoundingBox.\n"
"std_msgs/Header header\n"
"BoundingBox box\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ainstein_radar_msgs/BoundingBox\n"
"# BoundingBox represents a oriented bounding box.\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)\n"
"# You can use this field to hold value such as likelihood\n"
"float32 value\n"
"uint32 label\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.box);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBoxStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::BoundingBoxStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "box: ";
    s << std::endl;
    Printer< ::ainstein_radar_msgs::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.box);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_BOUNDINGBOXSTAMPED_H
