// Generated by gencpp from file ainstein_radar_msgs/RadarTargetStamped.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_RADARTARGETSTAMPED_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_RADARTARGETSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ainstein_radar_msgs/RadarTarget.h>

namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct RadarTargetStamped_
{
  typedef RadarTargetStamped_<ContainerAllocator> Type;

  RadarTargetStamped_()
    : header()
    , target()  {
    }
  RadarTargetStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , target(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator>  _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> const> ConstPtr;

}; // struct RadarTargetStamped_

typedef ::ainstein_radar_msgs::RadarTargetStamped_<std::allocator<void> > RadarTargetStamped;

typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTargetStamped > RadarTargetStampedPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTargetStamped const> RadarTargetStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1fbe9d124fcb7889ff4a0fa4df5665a";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1fbe9d124fcb788ULL;
  static const uint64_t static_value2 = 0x9ff4a0fa4df5665aULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/RadarTargetStamped";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes a target (detection) from a RADAR sensor with a timestamp.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"RadarTarget target\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ainstein_radar_msgs/RadarTarget\n"
"# This message describes a target (detection) from a RADAR sensor.\n"
"\n"
"uint16 target_id    # ID of the target, as set by the sensor\n"
"float64 snr         # Signal-to-noise ratio\n"
"float64 range       # Distance from sensor to target along sensor x-axis\n"
"float64 speed       # Speed (range rate of change) of target along sensor x-axis\n"
"float64 azimuth     # Angle of target relative to sensor within x-y plane\n"
"float64 elevation   # Angle of target relative to sensor within y-z plane\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarTargetStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::RadarTargetStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "target: ";
    s << std::endl;
    Printer< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_RADARTARGETSTAMPED_H
