// Generated by gencpp from file ainstein_radar_msgs/RadarInfo.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_RADARINFO_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_RADARINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct RadarInfo_
{
  typedef RadarInfo_<ContainerAllocator> Type;

  RadarInfo_()
    : header()
    , update_rate(0.0)
    , max_num_targets(0)
    , range_min(0.0)
    , range_max(0.0)
    , speed_min(0.0)
    , speed_max(0.0)
    , azimuth_min(0.0)
    , azimuth_max(0.0)
    , elevation_min(0.0)
    , elevation_max(0.0)
    , range_resolution(0.0)
    , range_accuracy(0.0)
    , speed_resolution(0.0)
    , speed_accuracy(0.0)
    , azimuth_resolution(0.0)
    , azimuth_accuracy(0.0)
    , elevation_resolution(0.0)
    , elevation_accuracy(0.0)  {
    }
  RadarInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , update_rate(0.0)
    , max_num_targets(0)
    , range_min(0.0)
    , range_max(0.0)
    , speed_min(0.0)
    , speed_max(0.0)
    , azimuth_min(0.0)
    , azimuth_max(0.0)
    , elevation_min(0.0)
    , elevation_max(0.0)
    , range_resolution(0.0)
    , range_accuracy(0.0)
    , speed_resolution(0.0)
    , speed_accuracy(0.0)
    , azimuth_resolution(0.0)
    , azimuth_accuracy(0.0)
    , elevation_resolution(0.0)
    , elevation_accuracy(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _update_rate_type;
  _update_rate_type update_rate;

   typedef uint16_t _max_num_targets_type;
  _max_num_targets_type max_num_targets;

   typedef double _range_min_type;
  _range_min_type range_min;

   typedef double _range_max_type;
  _range_max_type range_max;

   typedef double _speed_min_type;
  _speed_min_type speed_min;

   typedef double _speed_max_type;
  _speed_max_type speed_max;

   typedef double _azimuth_min_type;
  _azimuth_min_type azimuth_min;

   typedef double _azimuth_max_type;
  _azimuth_max_type azimuth_max;

   typedef double _elevation_min_type;
  _elevation_min_type elevation_min;

   typedef double _elevation_max_type;
  _elevation_max_type elevation_max;

   typedef double _range_resolution_type;
  _range_resolution_type range_resolution;

   typedef double _range_accuracy_type;
  _range_accuracy_type range_accuracy;

   typedef double _speed_resolution_type;
  _speed_resolution_type speed_resolution;

   typedef double _speed_accuracy_type;
  _speed_accuracy_type speed_accuracy;

   typedef double _azimuth_resolution_type;
  _azimuth_resolution_type azimuth_resolution;

   typedef double _azimuth_accuracy_type;
  _azimuth_accuracy_type azimuth_accuracy;

   typedef double _elevation_resolution_type;
  _elevation_resolution_type elevation_resolution;

   typedef double _elevation_accuracy_type;
  _elevation_accuracy_type elevation_accuracy;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RadarInfo_

typedef ::ainstein_radar_msgs::RadarInfo_<std::allocator<void> > RadarInfo;

typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarInfo > RadarInfoPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarInfo const> RadarInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.update_rate == rhs.update_rate &&
    lhs.max_num_targets == rhs.max_num_targets &&
    lhs.range_min == rhs.range_min &&
    lhs.range_max == rhs.range_max &&
    lhs.speed_min == rhs.speed_min &&
    lhs.speed_max == rhs.speed_max &&
    lhs.azimuth_min == rhs.azimuth_min &&
    lhs.azimuth_max == rhs.azimuth_max &&
    lhs.elevation_min == rhs.elevation_min &&
    lhs.elevation_max == rhs.elevation_max &&
    lhs.range_resolution == rhs.range_resolution &&
    lhs.range_accuracy == rhs.range_accuracy &&
    lhs.speed_resolution == rhs.speed_resolution &&
    lhs.speed_accuracy == rhs.speed_accuracy &&
    lhs.azimuth_resolution == rhs.azimuth_resolution &&
    lhs.azimuth_accuracy == rhs.azimuth_accuracy &&
    lhs.elevation_resolution == rhs.elevation_resolution &&
    lhs.elevation_accuracy == rhs.elevation_accuracy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "517f7ed5e498f66b6af3caaa2c6f2059";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x517f7ed5e498f66bULL;
  static const uint64_t static_value2 = 0x6af3caaa2c6f2059ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/RadarInfo";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message defines meta information for a radar sensor. It should\n"
"# be in a radar namespace on topic \"radar_info\" and accompanied by up\n"
"# to three radar topics named:\n"
"#\n"
"#   targets/raw      - raw (untracked) radar detections\n"
"#   targets/tracked  - tracked radar detections\n"
"#   alarms           - alarms based on detections, eg BSD\n"
"#\n"
"# In general, all Ainstein radars output raw detections and may also\n"
"# output tracked detections if trackign algorithms are implemented in\n"
"# firmware. Tracking from raw data is also available in ROS; see the\n"
"# ainstein_radar_filters package for more information. Most radars do\n"
"# not output alarms as this is specific to the automotive use case,\n"
"# however this message type is retained for the time being for backward\n"
"# compatibility.\n"
"\n"
"#######################################################################\n"
"#                     Data acquisition info                           #\n"
"#######################################################################\n"
"\n"
"# Time of data acquisition, radar coordinate frame ID\n"
"Header header    # Header timestamp should be acquisition time of data\n"
"                 # Header frame_id should be radar sensing frame\n"
"                 # origin of frame should be center of sensor\n"
"                 # +x should point radially outwards from the radar\n"
"                 # +y should point to complete a right-handed frame\n"
"                 # +z should point upwards\n"
"\n"
"#######################################################################\n"
"#                    General sensor properties                        #\n"
"#######################################################################\n"
"\n"
"# The nominal update rate of the sensor reported in Hz.\n"
"float64 update_rate\n"
"\n"
"# The maximum number of detections (targets) the sensors can report.\n"
"uint16 max_num_targets\n"
"\n"
"#######################################################################\n"
"#                    Physical sensing limits                          #\n"
"#######################################################################\n"
"# These are limits imposed by the antenna hardware and/or cutoffs set #\n"
"# in the detection processing firmware. They come from sensor data    #\n"
"# sheets and must be updated with each hardware revision as necessary.#\n"
"#######################################################################\n"
"\n"
"# The minimum and maximum range, in meters, of detections (targets)\n"
"# reported by the sensor.\n"
"float64 range_min\n"
"float64 range_max\n"
"\n"
"# The minimum and maximum speed, in meters per second, of detections\n"
"# (targets) reported by the sensor.\n"
"float64 speed_min\n"
"float64 speed_max\n"
"\n"
"# The minimum and maximum azimuth angle, in degrees.\n"
"float64 azimuth_min\n"
"float64 azimuth_max\n"
"\n"
"# The minimum and maximum azimuth angle, in degrees.\n"
"float64 elevation_min\n"
"float64 elevation_max\n"
"\n"
"#######################################################################\n"
"#                    Physical sensing precision                       #\n"
"#######################################################################\n"
"# These are also imposed by the antenna hardware and/or set in the    #\n"
"# detection processing firmware. They also come from sensor data      #\n"
"# sheets and must be updated with each hardware revision as necessary.#\n"
"#######################################################################\n"
"\n"
"# Range resolution, in meters. The resolution is defined as the minimum\n"
"# distance between two objects which results in distinct detections.\n"
"float64 range_resolution\n"
"\n"
"# Range accuracy, in meters. The accuracy is defined as the precision\n"
"# with which range of a detection is reported.\n"
"float64 range_accuracy\n"
"\n"
"# Speed resolution, in meters per second. The resolution is defined as\n"
"# the minimum speed difference between two objects which results in\n"
"# distinct detections.\n"
"float64 speed_resolution\n"
"\n"
"# Speed accuracy, in meters per second. The accuracy is defined as the\n"
"# precision with which speed of a detection is reported.\n"
"float64 speed_accuracy\n"
"\n"
"# Azimuth angle resolution, in degrees. The resolution is defined as\n"
"# the minimum azimuth angle between two objects which results in\n"
"# distinct detections.\n"
"float64 azimuth_resolution\n"
"\n"
"# Azimuth angle accuracy, in degrees. The accuracy is defined as the\n"
"# precision with which the azimuth angle of a detection is reported.\n"
"float64 azimuth_accuracy\n"
"\n"
"# Elevation angle resolution, in degrees. The resolution is defined as\n"
"# the minimum elevation angle between two objects which results in\n"
"# distinct detections.\n"
"float64 elevation_resolution\n"
"\n"
"# Elevation angle accuracy, in degrees. The accuracy is defined as the\n"
"# precision with which the elevation angle of a detection is reported.\n"
"float64 elevation_accuracy\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.update_rate);
      stream.next(m.max_num_targets);
      stream.next(m.range_min);
      stream.next(m.range_max);
      stream.next(m.speed_min);
      stream.next(m.speed_max);
      stream.next(m.azimuth_min);
      stream.next(m.azimuth_max);
      stream.next(m.elevation_min);
      stream.next(m.elevation_max);
      stream.next(m.range_resolution);
      stream.next(m.range_accuracy);
      stream.next(m.speed_resolution);
      stream.next(m.speed_accuracy);
      stream.next(m.azimuth_resolution);
      stream.next(m.azimuth_accuracy);
      stream.next(m.elevation_resolution);
      stream.next(m.elevation_accuracy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::RadarInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "update_rate: ";
    Printer<double>::stream(s, indent + "  ", v.update_rate);
    s << indent << "max_num_targets: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.max_num_targets);
    s << indent << "range_min: ";
    Printer<double>::stream(s, indent + "  ", v.range_min);
    s << indent << "range_max: ";
    Printer<double>::stream(s, indent + "  ", v.range_max);
    s << indent << "speed_min: ";
    Printer<double>::stream(s, indent + "  ", v.speed_min);
    s << indent << "speed_max: ";
    Printer<double>::stream(s, indent + "  ", v.speed_max);
    s << indent << "azimuth_min: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth_min);
    s << indent << "azimuth_max: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth_max);
    s << indent << "elevation_min: ";
    Printer<double>::stream(s, indent + "  ", v.elevation_min);
    s << indent << "elevation_max: ";
    Printer<double>::stream(s, indent + "  ", v.elevation_max);
    s << indent << "range_resolution: ";
    Printer<double>::stream(s, indent + "  ", v.range_resolution);
    s << indent << "range_accuracy: ";
    Printer<double>::stream(s, indent + "  ", v.range_accuracy);
    s << indent << "speed_resolution: ";
    Printer<double>::stream(s, indent + "  ", v.speed_resolution);
    s << indent << "speed_accuracy: ";
    Printer<double>::stream(s, indent + "  ", v.speed_accuracy);
    s << indent << "azimuth_resolution: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth_resolution);
    s << indent << "azimuth_accuracy: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth_accuracy);
    s << indent << "elevation_resolution: ";
    Printer<double>::stream(s, indent + "  ", v.elevation_resolution);
    s << indent << "elevation_accuracy: ";
    Printer<double>::stream(s, indent + "  ", v.elevation_accuracy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_RADARINFO_H
