// Generated by gencpp from file ainstein_radar_msgs/RadarAlarm.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARM_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct RadarAlarm_
{
  typedef RadarAlarm_<ContainerAllocator> Type;

  RadarAlarm_()
    : LCA_alarm(false)
    , CVW_alarm(false)
    , BSD_alarm(false)  {
    }
  RadarAlarm_(const ContainerAllocator& _alloc)
    : LCA_alarm(false)
    , CVW_alarm(false)
    , BSD_alarm(false)  {
  (void)_alloc;
    }



   typedef uint8_t _LCA_alarm_type;
  _LCA_alarm_type LCA_alarm;

   typedef uint8_t _CVW_alarm_type;
  _CVW_alarm_type CVW_alarm;

   typedef uint8_t _BSD_alarm_type;
  _BSD_alarm_type BSD_alarm;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> const> ConstPtr;

}; // struct RadarAlarm_

typedef ::ainstein_radar_msgs::RadarAlarm_<std::allocator<void> > RadarAlarm;

typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarm > RadarAlarmPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarm const> RadarAlarmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator2> & rhs)
{
  return lhs.LCA_alarm == rhs.LCA_alarm &&
    lhs.CVW_alarm == rhs.CVW_alarm &&
    lhs.BSD_alarm == rhs.BSD_alarm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf40054820bd713d25eca0cd48632dd2";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf40054820bd713dULL;
  static const uint64_t static_value2 = 0x25eca0cd48632dd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/RadarAlarm";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes alarms (eg BSD) from a RADAR sensor.\n"
"\n"
"bool LCA_alarm    # Lane Change Assist alarm\n"
"bool CVW_alarm    # Collision (Vehicle?) Warning alarm\n"
"bool BSD_alarm    # Blind Spot Detection alarm\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LCA_alarm);
      stream.next(m.CVW_alarm);
      stream.next(m.BSD_alarm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarAlarm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator>& v)
  {
    s << indent << "LCA_alarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LCA_alarm);
    s << indent << "CVW_alarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CVW_alarm);
    s << indent << "BSD_alarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BSD_alarm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARM_H
