// Generated by gencpp from file ainstein_radar_msgs/RadarTarget.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_RADARTARGET_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_RADARTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct RadarTarget_
{
  typedef RadarTarget_<ContainerAllocator> Type;

  RadarTarget_()
    : target_id(0)
    , snr(0.0)
    , range(0.0)
    , speed(0.0)
    , azimuth(0.0)
    , elevation(0.0)  {
    }
  RadarTarget_(const ContainerAllocator& _alloc)
    : target_id(0)
    , snr(0.0)
    , range(0.0)
    , speed(0.0)
    , azimuth(0.0)
    , elevation(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _target_id_type;
  _target_id_type target_id;

   typedef double _snr_type;
  _snr_type snr;

   typedef double _range_type;
  _range_type range;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _azimuth_type;
  _azimuth_type azimuth;

   typedef double _elevation_type;
  _elevation_type elevation;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> const> ConstPtr;

}; // struct RadarTarget_

typedef ::ainstein_radar_msgs::RadarTarget_<std::allocator<void> > RadarTarget;

typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTarget > RadarTargetPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTarget const> RadarTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator2> & rhs)
{
  return lhs.target_id == rhs.target_id &&
    lhs.snr == rhs.snr &&
    lhs.range == rhs.range &&
    lhs.speed == rhs.speed &&
    lhs.azimuth == rhs.azimuth &&
    lhs.elevation == rhs.elevation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "942d59f5ed2080c1747d5b79ce6dc1c0";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x942d59f5ed2080c1ULL;
  static const uint64_t static_value2 = 0x747d5b79ce6dc1c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/RadarTarget";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes a target (detection) from a RADAR sensor.\n"
"\n"
"uint16 target_id    # ID of the target, as set by the sensor\n"
"float64 snr         # Signal-to-noise ratio\n"
"float64 range       # Distance from sensor to target along sensor x-axis\n"
"float64 speed       # Speed (range rate of change) of target along sensor x-axis\n"
"float64 azimuth     # Angle of target relative to sensor within x-y plane\n"
"float64 elevation   # Angle of target relative to sensor within y-z plane\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_id);
      stream.next(m.snr);
      stream.next(m.range);
      stream.next(m.speed);
      stream.next(m.azimuth);
      stream.next(m.elevation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::RadarTarget_<ContainerAllocator>& v)
  {
    s << indent << "target_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target_id);
    s << indent << "snr: ";
    Printer<double>::stream(s, indent + "  ", v.snr);
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "azimuth: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth);
    s << indent << "elevation: ";
    Printer<double>::stream(s, indent + "  ", v.elevation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_RADARTARGET_H
