// Generated by gencpp from file ainstein_radar_msgs/RadarTrackedObject.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_RADARTRACKEDOBJECT_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_RADARTRACKEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <ainstein_radar_msgs/BoundingBox.h>

namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct RadarTrackedObject_
{
  typedef RadarTrackedObject_<ContainerAllocator> Type;

  RadarTrackedObject_()
    : id(0)
    , pose()
    , velocity()
    , box()  {
    }
  RadarTrackedObject_(const ContainerAllocator& _alloc)
    : id(0)
    , pose(_alloc)
    , velocity(_alloc)
    , box(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::ainstein_radar_msgs::BoundingBox_<ContainerAllocator>  _box_type;
  _box_type box;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> const> ConstPtr;

}; // struct RadarTrackedObject_

typedef ::ainstein_radar_msgs::RadarTrackedObject_<std::allocator<void> > RadarTrackedObject;

typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTrackedObject > RadarTrackedObjectPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarTrackedObject const> RadarTrackedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose &&
    lhs.velocity == rhs.velocity &&
    lhs.box == rhs.box;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a71462f8c844a31b18d0564b8ff5905";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a71462f8c844a31ULL;
  static const uint64_t static_value2 = 0xb18d0564b8ff5905ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/RadarTrackedObject";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes a tracked object from a RADAR sensor.\n"
"\n"
"uint16 id                    # Unique object identifier\n"
"\n"
"geometry_msgs/Pose pose      # Cartesian position and orientation\n"
"geometry_msgs/Twist velocity # Cartesian linear and angular velocity (twist)\n"
"\n"
"BoundingBox box              # Bounding box of associated raw detections\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: ainstein_radar_msgs/BoundingBox\n"
"# BoundingBox represents a oriented bounding box.\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)\n"
"# You can use this field to hold value such as likelihood\n"
"float32 value\n"
"uint32 label\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
      stream.next(m.velocity);
      stream.next(m.box);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarTrackedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::RadarTrackedObject_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "box: ";
    s << std::endl;
    Printer< ::ainstein_radar_msgs::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.box);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_RADARTRACKEDOBJECT_H
