// Generated by gencpp from file ainstein_radar_msgs/RadarAlarmArray.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARMARRAY_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARMARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ainstein_radar_msgs/RadarAlarm.h>

namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct RadarAlarmArray_
{
  typedef RadarAlarmArray_<ContainerAllocator> Type;

  RadarAlarmArray_()
    : header()
    , alarms()  {
    }
  RadarAlarmArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , alarms(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >> _alarms_type;
  _alarms_type alarms;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> const> ConstPtr;

}; // struct RadarAlarmArray_

typedef ::ainstein_radar_msgs::RadarAlarmArray_<std::allocator<void> > RadarAlarmArray;

typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarmArray > RadarAlarmArrayPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarmArray const> RadarAlarmArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.alarms == rhs.alarms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2ed2b28cdaf4bd421182c41d9016e57";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2ed2b28cdaf4bd4ULL;
  static const uint64_t static_value2 = 0x21182c41d9016e57ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/RadarAlarmArray";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes an array of alarms with a timestamp.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"RadarAlarm[] alarms\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ainstein_radar_msgs/RadarAlarm\n"
"# This message describes alarms (eg BSD) from a RADAR sensor.\n"
"\n"
"bool LCA_alarm    # Lane Change Assist alarm\n"
"bool CVW_alarm    # Collision (Vehicle?) Warning alarm\n"
"bool BSD_alarm    # Blind Spot Detection alarm\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.alarms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarAlarmArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::RadarAlarmArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "alarms[]" << std::endl;
    for (size_t i = 0; i < v.alarms.size(); ++i)
    {
      s << indent << "  alarms[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ainstein_radar_msgs::RadarAlarm_<ContainerAllocator> >::stream(s, indent + "    ", v.alarms[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARMARRAY_H
