// Generated by gencpp from file ainstein_radar_msgs/RadarAlarmStamped.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARMSTAMPED_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARMSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct RadarAlarmStamped_
{
  typedef RadarAlarmStamped_<ContainerAllocator> Type;

  RadarAlarmStamped_()
    : header()
    , LCA_alarm(false)
    , CVW_alarm(false)
    , BSD_alarm(false)  {
    }
  RadarAlarmStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , LCA_alarm(false)
    , CVW_alarm(false)
    , BSD_alarm(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _LCA_alarm_type;
  _LCA_alarm_type LCA_alarm;

   typedef uint8_t _CVW_alarm_type;
  _CVW_alarm_type CVW_alarm;

   typedef uint8_t _BSD_alarm_type;
  _BSD_alarm_type BSD_alarm;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> const> ConstPtr;

}; // struct RadarAlarmStamped_

typedef ::ainstein_radar_msgs::RadarAlarmStamped_<std::allocator<void> > RadarAlarmStamped;

typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarmStamped > RadarAlarmStampedPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::RadarAlarmStamped const> RadarAlarmStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.LCA_alarm == rhs.LCA_alarm &&
    lhs.CVW_alarm == rhs.CVW_alarm &&
    lhs.BSD_alarm == rhs.BSD_alarm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8302a7df5f42db7b8e1cc9a4e4b392a";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8302a7df5f42db7ULL;
  static const uint64_t static_value2 = 0xb8e1cc9a4e4b392aULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/RadarAlarmStamped";
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes alarms (eg BSD) from a RADAR sensor.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"bool LCA_alarm    # Lane Change Assist alarm\n"
"bool CVW_alarm    # Collision (Vehicle?) Warning alarm\n"
"bool BSD_alarm    # Blind Spot Detection alarm\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.LCA_alarm);
      stream.next(m.CVW_alarm);
      stream.next(m.BSD_alarm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarAlarmStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::RadarAlarmStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "LCA_alarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LCA_alarm);
    s << indent << "CVW_alarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CVW_alarm);
    s << indent << "BSD_alarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BSD_alarm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_RADARALARMSTAMPED_H
