// Generated by gencpp from file ainstein_radar_msgs/TwistArray.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_MSGS_MESSAGE_TWISTARRAY_H
#define AINSTEIN_RADAR_MSGS_MESSAGE_TWISTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Twist.h>

namespace ainstein_radar_msgs
{
template <class ContainerAllocator>
struct TwistArray_
{
  typedef TwistArray_<ContainerAllocator> Type;

  TwistArray_()
    : header()
    , velocities()  {
    }
  TwistArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocities(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Twist_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Twist_<ContainerAllocator> >> _velocities_type;
  _velocities_type velocities;





  typedef boost::shared_ptr< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> const> ConstPtr;

}; // struct TwistArray_

typedef ::ainstein_radar_msgs::TwistArray_<std::allocator<void> > TwistArray;

typedef boost::shared_ptr< ::ainstein_radar_msgs::TwistArray > TwistArrayPtr;
typedef boost::shared_ptr< ::ainstein_radar_msgs::TwistArray const> TwistArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.velocities == rhs.velocities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator1> & lhs, const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99d5a4212addb6ebc7a7ca0c92f09c0a";
  }

  static const char* value(const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99d5a4212addb6ebULL;
  static const uint64_t static_value2 = 0xc7a7ca0c92f09c0aULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_msgs/TwistArray";
  }

  static const char* value(const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes an array of targets with a timestamp.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"geometry_msgs/Twist[] velocities\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwistArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_msgs::TwistArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_msgs::TwistArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "    ", v.velocities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_MSGS_MESSAGE_TWISTARRAY_H
