(cl:in-package ainstein_radar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          UPDATE_RATE-VAL
          UPDATE_RATE
          MAX_NUM_TARGETS-VAL
          MAX_NUM_TARGETS
          RANGE_MIN-VAL
          RANGE_MIN
          RANGE_MAX-VAL
          RANGE_MAX
          SPEED_MIN-VAL
          SPEED_MIN
          SPEED_MAX-VAL
          SPEED_MAX
          AZIMUTH_MIN-VAL
          AZIMUTH_MIN
          AZIMUTH_MAX-VAL
          AZIMUTH_MAX
          ELEVATION_MIN-VAL
          ELEVATION_MIN
          ELEVATION_MAX-VAL
          ELEVATION_MAX
          RANGE_RESOLUTION-VAL
          RANGE_RESOLUTION
          RANGE_ACCURACY-VAL
          RANGE_ACCURACY
          SPEED_RESOLUTION-VAL
          SPEED_RESOLUTION
          SPEED_ACCURACY-VAL
          SPEED_ACCURACY
          AZIMUTH_RESOLUTION-VAL
          AZIMUTH_RESOLUTION
          AZIMUTH_ACCURACY-VAL
          AZIMUTH_ACCURACY
          ELEVATION_RESOLUTION-VAL
          ELEVATION_RESOLUTION
          ELEVATION_ACCURACY-VAL
          ELEVATION_ACCURACY
))