
(cl:in-package :asdf)

(defsystem "ainstein_radar_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :geometry_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "BoundingBox" :depends-on ("_package_BoundingBox"))
    (:file "_package_BoundingBox" :depends-on ("_package"))
    (:file "BoundingBoxArray" :depends-on ("_package_BoundingBoxArray"))
    (:file "_package_BoundingBoxArray" :depends-on ("_package"))
    (:file "BoundingBoxStamped" :depends-on ("_package_BoundingBoxStamped"))
    (:file "_package_BoundingBoxStamped" :depends-on ("_package"))
    (:file "RadarAlarm" :depends-on ("_package_RadarAlarm"))
    (:file "_package_RadarAlarm" :depends-on ("_package"))
    (:file "RadarAlarmArray" :depends-on ("_package_RadarAlarmArray"))
    (:file "_package_RadarAlarmArray" :depends-on ("_package"))
    (:file "RadarAlarmStamped" :depends-on ("_package_RadarAlarmStamped"))
    (:file "_package_RadarAlarmStamped" :depends-on ("_package"))
    (:file "RadarInfo" :depends-on ("_package_RadarInfo"))
    (:file "_package_RadarInfo" :depends-on ("_package"))
    (:file "RadarTarget" :depends-on ("_package_RadarTarget"))
    (:file "_package_RadarTarget" :depends-on ("_package"))
    (:file "RadarTargetArray" :depends-on ("_package_RadarTargetArray"))
    (:file "_package_RadarTargetArray" :depends-on ("_package"))
    (:file "RadarTargetStamped" :depends-on ("_package_RadarTargetStamped"))
    (:file "_package_RadarTargetStamped" :depends-on ("_package"))
    (:file "RadarTrackedObject" :depends-on ("_package_RadarTrackedObject"))
    (:file "_package_RadarTrackedObject" :depends-on ("_package"))
    (:file "RadarTrackedObjectArray" :depends-on ("_package_RadarTrackedObjectArray"))
    (:file "_package_RadarTrackedObjectArray" :depends-on ("_package"))
    (:file "RadarTrackedObjectStamped" :depends-on ("_package_RadarTrackedObjectStamped"))
    (:file "_package_RadarTrackedObjectStamped" :depends-on ("_package"))
    (:file "TwistArray" :depends-on ("_package_TwistArray"))
    (:file "_package_TwistArray" :depends-on ("_package"))
  ))