//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the ainstein_radar_filters package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __ainstein_radar_filters__POINTCLOUDDEBUGCONFIG_H__
#define __ainstein_radar_filters__POINTCLOUDDEBUGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace ainstein_radar_filters
{
  class PointCloudDebugConfigStatics;

  class PointCloudDebugConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(PointCloudDebugConfig &config, const PointCloudDebugConfig &max, const PointCloudDebugConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PointCloudDebugConfig &config1, const PointCloudDebugConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PointCloudDebugConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PointCloudDebugConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PointCloudDebugConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PointCloudDebugConfig &config) const = 0;
      virtual void getValue(const PointCloudDebugConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PointCloudDebugConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T PointCloudDebugConfig::* field;

      virtual void clamp(PointCloudDebugConfig &config, const PointCloudDebugConfig &max, const PointCloudDebugConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PointCloudDebugConfig &config1, const PointCloudDebugConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PointCloudDebugConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PointCloudDebugConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PointCloudDebugConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PointCloudDebugConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PointCloudDebugConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PointCloudDebugConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PointCloudDebugConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<PointCloudDebugConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PointCloudDebugConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("print_debug"==(*_i)->name){print_debug = boost::any_cast<bool>(val);}
        if("print_timestamp"==(*_i)->name){print_timestamp = boost::any_cast<bool>(val);}
        if("low_range_limit_m"==(*_i)->name){low_range_limit_m = boost::any_cast<double>(val);}
        if("high_range_limit_m"==(*_i)->name){high_range_limit_m = boost::any_cast<double>(val);}
        if("low_speed_limit_mps"==(*_i)->name){low_speed_limit_mps = boost::any_cast<double>(val);}
        if("high_speed_limit_mps"==(*_i)->name){high_speed_limit_mps = boost::any_cast<double>(val);}
        if("low_azimuth_limit_deg"==(*_i)->name){low_azimuth_limit_deg = boost::any_cast<double>(val);}
        if("high_azimuth_limit_deg"==(*_i)->name){high_azimuth_limit_deg = boost::any_cast<double>(val);}
        if("low_elevation_limit_deg"==(*_i)->name){low_elevation_limit_deg = boost::any_cast<double>(val);}
        if("high_elevation_limit_deg"==(*_i)->name){high_elevation_limit_deg = boost::any_cast<double>(val);}
        if("low_power_limit"==(*_i)->name){low_power_limit = boost::any_cast<double>(val);}
        if("high_power_limit"==(*_i)->name){high_power_limit = boost::any_cast<double>(val);}
      }
    }

    bool print_debug;
bool print_timestamp;
double low_range_limit_m;
double high_range_limit_m;
double low_speed_limit_mps;
double high_speed_limit_mps;
double low_azimuth_limit_deg;
double high_azimuth_limit_deg;
double low_elevation_limit_deg;
double high_elevation_limit_deg;
double low_power_limit;
double high_power_limit;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool print_debug;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool print_timestamp;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double low_range_limit_m;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double high_range_limit_m;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double low_speed_limit_mps;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double high_speed_limit_mps;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double low_azimuth_limit_deg;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double high_azimuth_limit_deg;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double low_elevation_limit_deg;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double high_elevation_limit_deg;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double low_power_limit;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double high_power_limit;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PointCloudDebugConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PointCloudDebugConfig &__max__ = __getMax__();
      const PointCloudDebugConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PointCloudDebugConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PointCloudDebugConfig &__getDefault__();
    static const PointCloudDebugConfig &__getMax__();
    static const PointCloudDebugConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PointCloudDebugConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PointCloudDebugConfig::ParamDescription<std::string>::clamp(PointCloudDebugConfig &config, const PointCloudDebugConfig &max, const PointCloudDebugConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PointCloudDebugConfigStatics
  {
    friend class PointCloudDebugConfig;

    PointCloudDebugConfigStatics()
    {
PointCloudDebugConfig::GroupDescription<PointCloudDebugConfig::DEFAULT, PointCloudDebugConfig> Default("Default", "", 0, 0, true, &PointCloudDebugConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.print_debug = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.print_debug = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.print_debug = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<bool>("print_debug", "bool", 0, "Enable debug message printing", "", &PointCloudDebugConfig::print_debug)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<bool>("print_debug", "bool", 0, "Enable debug message printing", "", &PointCloudDebugConfig::print_debug)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.print_timestamp = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.print_timestamp = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.print_timestamp = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<bool>("print_timestamp", "bool", 0, "Enable message timestamp printing", "", &PointCloudDebugConfig::print_timestamp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<bool>("print_timestamp", "bool", 0, "Enable message timestamp printing", "", &PointCloudDebugConfig::print_timestamp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.low_range_limit_m = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.low_range_limit_m = 25.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.low_range_limit_m = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_range_limit_m", "double", 0, "Low range limit for point cloud debug messages (m)", "", &PointCloudDebugConfig::low_range_limit_m)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_range_limit_m", "double", 0, "Low range limit for point cloud debug messages (m)", "", &PointCloudDebugConfig::low_range_limit_m)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.high_range_limit_m = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.high_range_limit_m = 25.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.high_range_limit_m = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_range_limit_m", "double", 0, "High range limit for point cloud debug messages (m)", "", &PointCloudDebugConfig::high_range_limit_m)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_range_limit_m", "double", 0, "High range limit for point cloud debug messages (m)", "", &PointCloudDebugConfig::high_range_limit_m)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.low_speed_limit_mps = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.low_speed_limit_mps = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.low_speed_limit_mps = -5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_speed_limit_mps", "double", 0, "Low speed limit for point cloud debug messages (m/s)", "", &PointCloudDebugConfig::low_speed_limit_mps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_speed_limit_mps", "double", 0, "Low speed limit for point cloud debug messages (m/s)", "", &PointCloudDebugConfig::low_speed_limit_mps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.high_speed_limit_mps = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.high_speed_limit_mps = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.high_speed_limit_mps = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_speed_limit_mps", "double", 0, "High speed limit for point cloud debug messages (m/s)", "", &PointCloudDebugConfig::high_speed_limit_mps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_speed_limit_mps", "double", 0, "High speed limit for point cloud debug messages (m/s)", "", &PointCloudDebugConfig::high_speed_limit_mps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.low_azimuth_limit_deg = -90.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.low_azimuth_limit_deg = 90.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.low_azimuth_limit_deg = -60.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_azimuth_limit_deg", "double", 0, "Low azimuth limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::low_azimuth_limit_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_azimuth_limit_deg", "double", 0, "Low azimuth limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::low_azimuth_limit_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.high_azimuth_limit_deg = -90.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.high_azimuth_limit_deg = 90.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.high_azimuth_limit_deg = 60.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_azimuth_limit_deg", "double", 0, "High azimuth limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::high_azimuth_limit_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_azimuth_limit_deg", "double", 0, "High azimuth limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::high_azimuth_limit_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.low_elevation_limit_deg = -90.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.low_elevation_limit_deg = 90.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.low_elevation_limit_deg = -60.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_elevation_limit_deg", "double", 0, "Low elevation limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::low_elevation_limit_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_elevation_limit_deg", "double", 0, "Low elevation limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::low_elevation_limit_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.high_elevation_limit_deg = -90.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.high_elevation_limit_deg = 90.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.high_elevation_limit_deg = 60.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_elevation_limit_deg", "double", 0, "High elevation limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::high_elevation_limit_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_elevation_limit_deg", "double", 0, "High elevation limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::high_elevation_limit_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.low_power_limit = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.low_power_limit = 65535.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.low_power_limit = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_power_limit", "double", 0, "Low power limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::low_power_limit)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("low_power_limit", "double", 0, "Low power limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::low_power_limit)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.high_power_limit = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.high_power_limit = 65535.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.high_power_limit = 65535.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_power_limit", "double", 0, "High elevation limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::high_power_limit)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PointCloudDebugConfig::AbstractParamDescriptionConstPtr(new PointCloudDebugConfig::ParamDescription<double>("high_power_limit", "double", 0, "High elevation limit for point cloud debug messages (deb)", "", &PointCloudDebugConfig::high_power_limit)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PointCloudDebugConfig::AbstractGroupDescriptionConstPtr(new PointCloudDebugConfig::GroupDescription<PointCloudDebugConfig::DEFAULT, PointCloudDebugConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PointCloudDebugConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PointCloudDebugConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PointCloudDebugConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PointCloudDebugConfig __max__;
    PointCloudDebugConfig __min__;
    PointCloudDebugConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PointCloudDebugConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PointCloudDebugConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PointCloudDebugConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PointCloudDebugConfig &PointCloudDebugConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PointCloudDebugConfig &PointCloudDebugConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PointCloudDebugConfig &PointCloudDebugConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PointCloudDebugConfig::AbstractParamDescriptionConstPtr> &PointCloudDebugConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PointCloudDebugConfig::AbstractGroupDescriptionConstPtr> &PointCloudDebugConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PointCloudDebugConfigStatics *PointCloudDebugConfig::__get_statics__()
  {
    const static PointCloudDebugConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PointCloudDebugConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __POINTCLOUDDEBUGRECONFIGURATOR_H__
