(cl:defpackage open3d_slam_msgs-srv
  (:use )
  (:export
   "FILEPATH"
   "<FILEPATH-REQUEST>"
   "FILEPATH-REQUEST"
   "<FILEPATH-RESPONSE>"
   "FILEPATH-RESPONSE"
   "SAVEMAP"
   "<SAVEMAP-REQUEST>"
   "SAVEMAP-REQUEST"
   "<SAVEMAP-RESPONSE>"
   "SAVEMAP-RESPONSE"
   "SAVESUBMAPS"
   "<SAVESUBMAPS-REQUEST>"
   "SAVESUBMAPS-REQUEST"
   "<SAVESUBMAPS-RESPONSE>"
   "SAVESUBMAPS-RESPONSE"
  ))

