// Generated by gencpp from file ainstein_radar_drivers/O79DeviceParams.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_DRIVERS_MESSAGE_O79DEVICEPARAMS_H
#define AINSTEIN_RADAR_DRIVERS_MESSAGE_O79DEVICEPARAMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainstein_radar_drivers
{
template <class ContainerAllocator>
struct O79DeviceParams_
{
  typedef O79DeviceParams_<ContainerAllocator> Type;

  O79DeviceParams_()
    : fw_version()
    , can_id()
    , serial_no()
    , mac_address()  {
    }
  O79DeviceParams_(const ContainerAllocator& _alloc)
    : fw_version(_alloc)
    , can_id(_alloc)
    , serial_no(_alloc)
    , mac_address(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _fw_version_type;
  _fw_version_type fw_version;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _can_id_type;
  _can_id_type can_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _serial_no_type;
  _serial_no_type serial_no;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mac_address_type;
  _mac_address_type mac_address;





  typedef boost::shared_ptr< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> const> ConstPtr;

}; // struct O79DeviceParams_

typedef ::ainstein_radar_drivers::O79DeviceParams_<std::allocator<void> > O79DeviceParams;

typedef boost::shared_ptr< ::ainstein_radar_drivers::O79DeviceParams > O79DeviceParamsPtr;
typedef boost::shared_ptr< ::ainstein_radar_drivers::O79DeviceParams const> O79DeviceParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator2> & rhs)
{
  return lhs.fw_version == rhs.fw_version &&
    lhs.can_id == rhs.can_id &&
    lhs.serial_no == rhs.serial_no &&
    lhs.mac_address == rhs.mac_address;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_drivers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9486679d9acc068b9eb160f4d0978a74";
  }

  static const char* value(const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9486679d9acc068bULL;
  static const uint64_t static_value2 = 0x9eb160f4d0978a74ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_drivers/O79DeviceParams";
  }

  static const char* value(const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes the O-79 imaging radar device parameters.\n"
"\n"
"string fw_version     # Firmware version\n"
"string can_id         # Radar CAN ID\n"
"string serial_no      # Radar serial number\n"
"string mac_address    # Radar MAC address\n"
;
  }

  static const char* value(const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fw_version);
      stream.next(m.can_id);
      stream.next(m.serial_no);
      stream.next(m.mac_address);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct O79DeviceParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_drivers::O79DeviceParams_<ContainerAllocator>& v)
  {
    s << indent << "fw_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.fw_version);
    s << indent << "can_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.can_id);
    s << indent << "serial_no: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.serial_no);
    s << indent << "mac_address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mac_address);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_DRIVERS_MESSAGE_O79DEVICEPARAMS_H
