// Generated by gencpp from file ainstein_radar_drivers/O79NetworkParams.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_DRIVERS_MESSAGE_O79NETWORKPARAMS_H
#define AINSTEIN_RADAR_DRIVERS_MESSAGE_O79NETWORKPARAMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainstein_radar_drivers
{
template <class ContainerAllocator>
struct O79NetworkParams_
{
  typedef O79NetworkParams_<ContainerAllocator> Type;

  O79NetworkParams_()
    : ip()
    , netmask()
    , gateway()
    , host_ip()
    , host_port(0)  {
    }
  O79NetworkParams_(const ContainerAllocator& _alloc)
    : ip(_alloc)
    , netmask(_alloc)
    , gateway(_alloc)
    , host_ip(_alloc)
    , host_port(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ip_type;
  _ip_type ip;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _netmask_type;
  _netmask_type netmask;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _gateway_type;
  _gateway_type gateway;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _host_ip_type;
  _host_ip_type host_ip;

   typedef uint16_t _host_port_type;
  _host_port_type host_port;





  typedef boost::shared_ptr< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> const> ConstPtr;

}; // struct O79NetworkParams_

typedef ::ainstein_radar_drivers::O79NetworkParams_<std::allocator<void> > O79NetworkParams;

typedef boost::shared_ptr< ::ainstein_radar_drivers::O79NetworkParams > O79NetworkParamsPtr;
typedef boost::shared_ptr< ::ainstein_radar_drivers::O79NetworkParams const> O79NetworkParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator2> & rhs)
{
  return lhs.ip == rhs.ip &&
    lhs.netmask == rhs.netmask &&
    lhs.gateway == rhs.gateway &&
    lhs.host_ip == rhs.host_ip &&
    lhs.host_port == rhs.host_port;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_drivers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a69287f037293465b761a7fa4a733b65";
  }

  static const char* value(const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa69287f037293465ULL;
  static const uint64_t static_value2 = 0xb761a7fa4a733b65ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_drivers/O79NetworkParams";
  }

  static const char* value(const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes the O-79 imaging radar network parameters.\n"
"\n"
"string ip           # Radar IP address\n"
"string netmask      # Radar network mask\n"
"string gateway      # Radar network gateway\n"
"string host_ip      # Host PC IP address\n"
"uint16 host_port    # Host PC port\n"
;
  }

  static const char* value(const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ip);
      stream.next(m.netmask);
      stream.next(m.gateway);
      stream.next(m.host_ip);
      stream.next(m.host_port);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct O79NetworkParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_drivers::O79NetworkParams_<ContainerAllocator>& v)
  {
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ip);
    s << indent << "netmask: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.netmask);
    s << indent << "gateway: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.gateway);
    s << indent << "host_ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.host_ip);
    s << indent << "host_port: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.host_port);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_DRIVERS_MESSAGE_O79NETWORKPARAMS_H
