// Generated by gencpp from file ainstein_radar_drivers/O79TrackingParams.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_DRIVERS_MESSAGE_O79TRACKINGPARAMS_H
#define AINSTEIN_RADAR_DRIVERS_MESSAGE_O79TRACKINGPARAMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainstein_radar_drivers
{
template <class ContainerAllocator>
struct O79TrackingParams_
{
  typedef O79TrackingParams_<ContainerAllocator> Type;

  O79TrackingParams_()
    : update_rate(0.0)
    , min_time(0.0)
    , timeout(0.0)
    , confidence_level(0.0)
    , proc_noise_speed(0.0)
    , proc_noise_azim(0.0)
    , proc_noise_elev(0.0)
    , min_range(0.0)
    , max_range(0.0)
    , proc_noise_vel_x(0.0)
    , proc_noise_vel_y(0.0)
    , proc_noise_vel_z(0.0)
    , meas_noise_speed(0.0)
    , meas_noise_pos(0.0)
    , filter_type(0)  {
    }
  O79TrackingParams_(const ContainerAllocator& _alloc)
    : update_rate(0.0)
    , min_time(0.0)
    , timeout(0.0)
    , confidence_level(0.0)
    , proc_noise_speed(0.0)
    , proc_noise_azim(0.0)
    , proc_noise_elev(0.0)
    , min_range(0.0)
    , max_range(0.0)
    , proc_noise_vel_x(0.0)
    , proc_noise_vel_y(0.0)
    , proc_noise_vel_z(0.0)
    , meas_noise_speed(0.0)
    , meas_noise_pos(0.0)
    , filter_type(0)  {
  (void)_alloc;
    }



   typedef float _update_rate_type;
  _update_rate_type update_rate;

   typedef float _min_time_type;
  _min_time_type min_time;

   typedef float _timeout_type;
  _timeout_type timeout;

   typedef float _confidence_level_type;
  _confidence_level_type confidence_level;

   typedef float _proc_noise_speed_type;
  _proc_noise_speed_type proc_noise_speed;

   typedef float _proc_noise_azim_type;
  _proc_noise_azim_type proc_noise_azim;

   typedef float _proc_noise_elev_type;
  _proc_noise_elev_type proc_noise_elev;

   typedef float _min_range_type;
  _min_range_type min_range;

   typedef float _max_range_type;
  _max_range_type max_range;

   typedef float _proc_noise_vel_x_type;
  _proc_noise_vel_x_type proc_noise_vel_x;

   typedef float _proc_noise_vel_y_type;
  _proc_noise_vel_y_type proc_noise_vel_y;

   typedef float _proc_noise_vel_z_type;
  _proc_noise_vel_z_type proc_noise_vel_z;

   typedef float _meas_noise_speed_type;
  _meas_noise_speed_type meas_noise_speed;

   typedef float _meas_noise_pos_type;
  _meas_noise_pos_type meas_noise_pos;

   typedef int8_t _filter_type_type;
  _filter_type_type filter_type;





  typedef boost::shared_ptr< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> const> ConstPtr;

}; // struct O79TrackingParams_

typedef ::ainstein_radar_drivers::O79TrackingParams_<std::allocator<void> > O79TrackingParams;

typedef boost::shared_ptr< ::ainstein_radar_drivers::O79TrackingParams > O79TrackingParamsPtr;
typedef boost::shared_ptr< ::ainstein_radar_drivers::O79TrackingParams const> O79TrackingParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator2> & rhs)
{
  return lhs.update_rate == rhs.update_rate &&
    lhs.min_time == rhs.min_time &&
    lhs.timeout == rhs.timeout &&
    lhs.confidence_level == rhs.confidence_level &&
    lhs.proc_noise_speed == rhs.proc_noise_speed &&
    lhs.proc_noise_azim == rhs.proc_noise_azim &&
    lhs.proc_noise_elev == rhs.proc_noise_elev &&
    lhs.min_range == rhs.min_range &&
    lhs.max_range == rhs.max_range &&
    lhs.proc_noise_vel_x == rhs.proc_noise_vel_x &&
    lhs.proc_noise_vel_y == rhs.proc_noise_vel_y &&
    lhs.proc_noise_vel_z == rhs.proc_noise_vel_z &&
    lhs.meas_noise_speed == rhs.meas_noise_speed &&
    lhs.meas_noise_pos == rhs.meas_noise_pos &&
    lhs.filter_type == rhs.filter_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_drivers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8794997c1f9ccf549a183253ff0fcb2e";
  }

  static const char* value(const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8794997c1f9ccf54ULL;
  static const uint64_t static_value2 = 0x9a183253ff0fcb2eULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_drivers/O79TrackingParams";
  }

  static const char* value(const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes the O-79 imaging radar tracking filter parameters.\n"
"\n"
"float32 update_rate\n"
"float32 min_time\n"
"float32 timeout\n"
"float32 confidence_level\n"
"float32 proc_noise_speed\n"
"float32 proc_noise_azim\n"
"float32 proc_noise_elev\n"
"float32 min_range\n"
"float32 max_range\n"
"float32 proc_noise_vel_x\n"
"float32 proc_noise_vel_y\n"
"float32 proc_noise_vel_z\n"
"float32 meas_noise_speed\n"
"float32 meas_noise_pos\n"
"int8 filter_type\n"
;
  }

  static const char* value(const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.update_rate);
      stream.next(m.min_time);
      stream.next(m.timeout);
      stream.next(m.confidence_level);
      stream.next(m.proc_noise_speed);
      stream.next(m.proc_noise_azim);
      stream.next(m.proc_noise_elev);
      stream.next(m.min_range);
      stream.next(m.max_range);
      stream.next(m.proc_noise_vel_x);
      stream.next(m.proc_noise_vel_y);
      stream.next(m.proc_noise_vel_z);
      stream.next(m.meas_noise_speed);
      stream.next(m.meas_noise_pos);
      stream.next(m.filter_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct O79TrackingParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_drivers::O79TrackingParams_<ContainerAllocator>& v)
  {
    s << indent << "update_rate: ";
    Printer<float>::stream(s, indent + "  ", v.update_rate);
    s << indent << "min_time: ";
    Printer<float>::stream(s, indent + "  ", v.min_time);
    s << indent << "timeout: ";
    Printer<float>::stream(s, indent + "  ", v.timeout);
    s << indent << "confidence_level: ";
    Printer<float>::stream(s, indent + "  ", v.confidence_level);
    s << indent << "proc_noise_speed: ";
    Printer<float>::stream(s, indent + "  ", v.proc_noise_speed);
    s << indent << "proc_noise_azim: ";
    Printer<float>::stream(s, indent + "  ", v.proc_noise_azim);
    s << indent << "proc_noise_elev: ";
    Printer<float>::stream(s, indent + "  ", v.proc_noise_elev);
    s << indent << "min_range: ";
    Printer<float>::stream(s, indent + "  ", v.min_range);
    s << indent << "max_range: ";
    Printer<float>::stream(s, indent + "  ", v.max_range);
    s << indent << "proc_noise_vel_x: ";
    Printer<float>::stream(s, indent + "  ", v.proc_noise_vel_x);
    s << indent << "proc_noise_vel_y: ";
    Printer<float>::stream(s, indent + "  ", v.proc_noise_vel_y);
    s << indent << "proc_noise_vel_z: ";
    Printer<float>::stream(s, indent + "  ", v.proc_noise_vel_z);
    s << indent << "meas_noise_speed: ";
    Printer<float>::stream(s, indent + "  ", v.meas_noise_speed);
    s << indent << "meas_noise_pos: ";
    Printer<float>::stream(s, indent + "  ", v.meas_noise_pos);
    s << indent << "filter_type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.filter_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_DRIVERS_MESSAGE_O79TRACKINGPARAMS_H
