// Generated by gencpp from file ainstein_radar_drivers/WayvAirConfiguration.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_DRIVERS_MESSAGE_WAYVAIRCONFIGURATION_H
#define AINSTEIN_RADAR_DRIVERS_MESSAGE_WAYVAIRCONFIGURATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ainstein_radar_drivers
{
template <class ContainerAllocator>
struct WayvAirConfiguration_
{
  typedef WayvAirConfiguration_<ContainerAllocator> Type;

  WayvAirConfiguration_()
    : fw_ver()
    , sbl_ver()
    , id_485(0)
    , baud_485(0)
    , server_ip()
    , server_port(0)
    , wifi_name()
    , wifi_pwd()
    , con_wifi_name()
    , con_wifi_pwd()
    , dev_id()
    , wifi_mode(0)
    , sys_mode(0)
    , radio_switch(0)
    , radio_time(0)
    , radar_conf()
    , radar_config_len(0)  {
    }
  WayvAirConfiguration_(const ContainerAllocator& _alloc)
    : fw_ver(_alloc)
    , sbl_ver(_alloc)
    , id_485(0)
    , baud_485(0)
    , server_ip(_alloc)
    , server_port(0)
    , wifi_name(_alloc)
    , wifi_pwd(_alloc)
    , con_wifi_name(_alloc)
    , con_wifi_pwd(_alloc)
    , dev_id(_alloc)
    , wifi_mode(0)
    , sys_mode(0)
    , radio_switch(0)
    , radio_time(0)
    , radar_conf(_alloc)
    , radar_config_len(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _fw_ver_type;
  _fw_ver_type fw_ver;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sbl_ver_type;
  _sbl_ver_type sbl_ver;

   typedef uint16_t _id_485_type;
  _id_485_type id_485;

   typedef uint32_t _baud_485_type;
  _baud_485_type baud_485;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _server_ip_type;
  _server_ip_type server_ip;

   typedef uint16_t _server_port_type;
  _server_port_type server_port;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _wifi_name_type;
  _wifi_name_type wifi_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _wifi_pwd_type;
  _wifi_pwd_type wifi_pwd;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _con_wifi_name_type;
  _con_wifi_name_type con_wifi_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _con_wifi_pwd_type;
  _con_wifi_pwd_type con_wifi_pwd;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dev_id_type;
  _dev_id_type dev_id;

   typedef uint16_t _wifi_mode_type;
  _wifi_mode_type wifi_mode;

   typedef uint16_t _sys_mode_type;
  _sys_mode_type sys_mode;

   typedef uint16_t _radio_switch_type;
  _radio_switch_type radio_switch;

   typedef uint16_t _radio_time_type;
  _radio_time_type radio_time;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _radar_conf_type;
  _radar_conf_type radar_conf;

   typedef uint16_t _radar_config_len_type;
  _radar_config_len_type radar_config_len;





  typedef boost::shared_ptr< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> const> ConstPtr;

}; // struct WayvAirConfiguration_

typedef ::ainstein_radar_drivers::WayvAirConfiguration_<std::allocator<void> > WayvAirConfiguration;

typedef boost::shared_ptr< ::ainstein_radar_drivers::WayvAirConfiguration > WayvAirConfigurationPtr;
typedef boost::shared_ptr< ::ainstein_radar_drivers::WayvAirConfiguration const> WayvAirConfigurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator2> & rhs)
{
  return lhs.fw_ver == rhs.fw_ver &&
    lhs.sbl_ver == rhs.sbl_ver &&
    lhs.id_485 == rhs.id_485 &&
    lhs.baud_485 == rhs.baud_485 &&
    lhs.server_ip == rhs.server_ip &&
    lhs.server_port == rhs.server_port &&
    lhs.wifi_name == rhs.wifi_name &&
    lhs.wifi_pwd == rhs.wifi_pwd &&
    lhs.con_wifi_name == rhs.con_wifi_name &&
    lhs.con_wifi_pwd == rhs.con_wifi_pwd &&
    lhs.dev_id == rhs.dev_id &&
    lhs.wifi_mode == rhs.wifi_mode &&
    lhs.sys_mode == rhs.sys_mode &&
    lhs.radio_switch == rhs.radio_switch &&
    lhs.radio_time == rhs.radio_time &&
    lhs.radar_conf == rhs.radar_conf &&
    lhs.radar_config_len == rhs.radar_config_len;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_drivers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "697324bcda4e9dd0d2b06e834f223a42";
  }

  static const char* value(const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x697324bcda4e9dd0ULL;
  static const uint64_t static_value2 = 0xd2b06e834f223a42ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_drivers/WayvAirConfiguration";
  }

  static const char* value(const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes the Wayv Air radar configuration parameters.\n"
"string fw_ver           # Firmware Version\n"
"string sbl_ver          # Bootloader Version\n"
"uint16 id_485           # 485 ID / Radar Comm ID\n"
"uint32 baud_485         # Serial Baud Rate\n"
"string server_ip        # Server IP address for Station Mode\n"
"uint16 server_port      # Server Port for Station Mode\n"
"string wifi_name        # WAYV (AP) broadcast Wifi Name\n"
"string wifi_pwd         # WAYV (AP) Broadcast Wifi Password\n"
"string con_wifi_name    # Station Mode Wifi Name\n"
"string con_wifi_pwd     # Station Mode Wifi Password\n"
"string dev_id           # Device Serial ID\n"
"uint16 wifi_mode        # AP mode (0) or Station mode(1)\n"
"uint16 sys_mode         # WAYV Operating Mode - Normal(0) - TLV(2) - TLV_Wifi(4)\n"
"uint16 radio_switch     # Radio Inactive (0) - Radio Inactive (1)\n"
"uint16 radio_time       #\n"
"string[] radar_conf       # Radar Configuration String\n"
"uint16 radar_config_len # Number of Radar Config Entries\n"
;
  }

  static const char* value(const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fw_ver);
      stream.next(m.sbl_ver);
      stream.next(m.id_485);
      stream.next(m.baud_485);
      stream.next(m.server_ip);
      stream.next(m.server_port);
      stream.next(m.wifi_name);
      stream.next(m.wifi_pwd);
      stream.next(m.con_wifi_name);
      stream.next(m.con_wifi_pwd);
      stream.next(m.dev_id);
      stream.next(m.wifi_mode);
      stream.next(m.sys_mode);
      stream.next(m.radio_switch);
      stream.next(m.radio_time);
      stream.next(m.radar_conf);
      stream.next(m.radar_config_len);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WayvAirConfiguration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_drivers::WayvAirConfiguration_<ContainerAllocator>& v)
  {
    s << indent << "fw_ver: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.fw_ver);
    s << indent << "sbl_ver: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sbl_ver);
    s << indent << "id_485: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id_485);
    s << indent << "baud_485: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.baud_485);
    s << indent << "server_ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.server_ip);
    s << indent << "server_port: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.server_port);
    s << indent << "wifi_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.wifi_name);
    s << indent << "wifi_pwd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.wifi_pwd);
    s << indent << "con_wifi_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.con_wifi_name);
    s << indent << "con_wifi_pwd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.con_wifi_pwd);
    s << indent << "dev_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dev_id);
    s << indent << "wifi_mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.wifi_mode);
    s << indent << "sys_mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sys_mode);
    s << indent << "radio_switch: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.radio_switch);
    s << indent << "radio_time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.radio_time);
    s << indent << "radar_conf[]" << std::endl;
    for (size_t i = 0; i < v.radar_conf.size(); ++i)
    {
      s << indent << "  radar_conf[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.radar_conf[i]);
    }
    s << indent << "radar_config_len: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.radar_config_len);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_DRIVERS_MESSAGE_WAYVAIRCONFIGURATION_H
