// Generated by gencpp from file ainstein_radar_drivers/WayvAirStatus.msg
// DO NOT EDIT!


#ifndef AINSTEIN_RADAR_DRIVERS_MESSAGE_WAYVAIRSTATUS_H
#define AINSTEIN_RADAR_DRIVERS_MESSAGE_WAYVAIRSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ainstein_radar_drivers
{
template <class ContainerAllocator>
struct WayvAirStatus_
{
  typedef WayvAirStatus_<ContainerAllocator> Type;

  WayvAirStatus_()
    : header()
    , board_temp(0.0)
    , tx_temps()
    , pm_temp(0.0)
    , voltage(0.0)
    , power(0.0)  {
    }
  WayvAirStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , board_temp(0.0)
    , tx_temps(_alloc)
    , pm_temp(0.0)
    , voltage(0.0)
    , power(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _board_temp_type;
  _board_temp_type board_temp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tx_temps_type;
  _tx_temps_type tx_temps;

   typedef float _pm_temp_type;
  _pm_temp_type pm_temp;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef float _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> const> ConstPtr;

}; // struct WayvAirStatus_

typedef ::ainstein_radar_drivers::WayvAirStatus_<std::allocator<void> > WayvAirStatus;

typedef boost::shared_ptr< ::ainstein_radar_drivers::WayvAirStatus > WayvAirStatusPtr;
typedef boost::shared_ptr< ::ainstein_radar_drivers::WayvAirStatus const> WayvAirStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.board_temp == rhs.board_temp &&
    lhs.tx_temps == rhs.tx_temps &&
    lhs.pm_temp == rhs.pm_temp &&
    lhs.voltage == rhs.voltage &&
    lhs.power == rhs.power;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator1> & lhs, const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ainstein_radar_drivers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb442fd5018b46ec3791154842d3c373";
  }

  static const char* value(const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb442fd5018b46ecULL;
  static const uint64_t static_value2 = 0x3791154842d3c373ULL;
};

template<class ContainerAllocator>
struct DataType< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ainstein_radar_drivers/WayvAirStatus";
  }

  static const char* value(const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes the Wayv Air radar device status.\n"
"\n"
"std_msgs/Header header\n"
"float32 board_temp     # Board temperature, *C\n"
"float32[] tx_temps     # Tx temperatures, *C\n"
"float32 pm_temp        # PM temperature, *C\n"
"float32 voltage        # Voltage, V\n"
"float32 power          # Power, mW\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.board_temp);
      stream.next(m.tx_temps);
      stream.next(m.pm_temp);
      stream.next(m.voltage);
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WayvAirStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ainstein_radar_drivers::WayvAirStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "board_temp: ";
    Printer<float>::stream(s, indent + "  ", v.board_temp);
    s << indent << "tx_temps[]" << std::endl;
    for (size_t i = 0; i < v.tx_temps.size(); ++i)
    {
      s << indent << "  tx_temps[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tx_temps[i]);
    }
    s << indent << "pm_temp: ";
    Printer<float>::stream(s, indent + "  ", v.pm_temp);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AINSTEIN_RADAR_DRIVERS_MESSAGE_WAYVAIRSTATUS_H
