(cl:in-package ainstein_radar_drivers-msg)
(cl:export '(UPDATE_RATE-VAL
          UPDATE_RATE
          MIN_TIME-VAL
          MIN_TIME
          TIMEOUT-VAL
          TIMEOUT
          CONFIDENCE_LEVEL-VAL
          CONFIDENCE_LEVEL
          PROC_NOISE_SPEED-VAL
          PROC_NOISE_SPEED
          PROC_NOISE_AZIM-VAL
          PROC_NOISE_AZIM
          PROC_NOISE_ELEV-VAL
          PROC_NOISE_ELEV
          MIN_RANGE-VAL
          MIN_RANGE
          MAX_RANGE-VAL
          MAX_RANGE
          PROC_NOISE_VEL_X-VAL
          PROC_NOISE_VEL_X
          PROC_NOISE_VEL_Y-VAL
          PROC_NOISE_VEL_Y
          PROC_NOISE_VEL_Z-VAL
          PROC_NOISE_VEL_Z
          MEAS_NOISE_SPEED-VAL
          MEAS_NOISE_SPEED
          MEAS_NOISE_POS-VAL
          MEAS_NOISE_POS
          FILTER_TYPE-VAL
          FILTER_TYPE
))