(cl:in-package ainstein_radar_drivers-msg)
(cl:export '(FW_VER-VAL
          FW_VER
          SBL_VER-VAL
          SBL_VER
          ID_485-VAL
          ID_485
          BAUD_485-VAL
          BAUD_485
          SERVER_IP-VAL
          SERVER_IP
          SERVER_PORT-VAL
          SERVER_PORT
          WIFI_NAME-VAL
          WIFI_NAME
          WIFI_PWD-VAL
          WIFI_PWD
          CON_WIFI_NAME-VAL
          CON_WIFI_NAME
          CON_WIFI_PWD-VAL
          CON_WIFI_PWD
          DEV_ID-VAL
          DEV_ID
          WIFI_MODE-VAL
          WIFI_MODE
          SYS_MODE-VAL
          SYS_MODE
          RADIO_SWITCH-VAL
          RADIO_SWITCH
          RADIO_TIME-VAL
          RADIO_TIME
          RADAR_CONF-VAL
          RADAR_CONF
          RADAR_CONFIG_LEN-VAL
          RADAR_CONFIG_LEN
))